name: Publish Maven Site

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to publish.'
        required: true
        default: 'master'
jobs:
  build:
    name: Publish maven site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          
      - name: Configure Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"  
      
      - name: Publish Site 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw -ntp -pl plugin -am --batch-mode clean compile site site:stage scm-publish:publish-scm
        

            

