name: Publish Maven Site

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish maven site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          server-id: github
          
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"  
      
      - name: Publish Site 
        run: ./mvnw -pl plugin -am --batch-mode clean compile site site:stage scm-publish:publish-scm

            

