name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release. Used as tag name.'
        required: true
        default: 'x.y.z'

jobs:
  build:
    name: Release pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.gpg_private_key }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Build bonita-project-maven-plugin release 
        run: ./mvnw --batch-mode release:prepare -DreleaseVersion=${{ github.event.inputs.version }}

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Create Github Release
        id: create_release
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{github.event.inputs.version}}',
              name: 'Release ${{github.event.inputs.version}}',
              body: ` ${{ steps.changelog.outputs.changes }} `
            })
            
      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.ossrh_username }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.ossrh_password }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
        run: mvn --batch-mode release:perform
