<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_f9YskDICEe6TLMi6_2y08A" name="Process8" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_f9YskTICEe6TLMi6_2y08A" name="Pool8">
      <elements xmi:type="process:Lane" xmi:id="_f9YskjICEe6TLMi6_2y08A" name="Employee lane" actor="_f9YsqzICEe6TLMi6_2y08A">
        <elements xmi:type="process:StartEvent" xmi:id="_f9YskzICEe6TLMi6_2y08A" name="Start1" outgoing="_f9YsqDICEe6TLMi6_2y08A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f9YslDICEe6TLMi6_2y08A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f9YslTICEe6TLMi6_2y08A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f9YsljICEe6TLMi6_2y08A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_f9YslzICEe6TLMi6_2y08A" name="Step1" incoming="_f9YsqDICEe6TLMi6_2y08A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f9YsmDICEe6TLMi6_2y08A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f9YsmTICEe6TLMi6_2y08A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f9YsmjICEe6TLMi6_2y08A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_f9YsmzICEe6TLMi6_2y08A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_f9YsnDICEe6TLMi6_2y08A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_f9YsnTICEe6TLMi6_2y08A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_f9YsnjICEe6TLMi6_2y08A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_f9YsnzICEe6TLMi6_2y08A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_f9YsoDICEe6TLMi6_2y08A">
            <targetForm xmi:type="expression:Expression" xmi:id="_f9YsoTICEe6TLMi6_2y08A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_f9YsojICEe6TLMi6_2y08A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_f9YsozICEe6TLMi6_2y08A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_f9YspDICEe6TLMi6_2y08A">
        <targetForm xmi:type="expression:Expression" xmi:id="_f9YspTICEe6TLMi6_2y08A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_f9YspjICEe6TLMi6_2y08A">
        <targetForm xmi:type="expression:Expression" xmi:id="_f9YspzICEe6TLMi6_2y08A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_f9YsqDICEe6TLMi6_2y08A" target="_f9YslzICEe6TLMi6_2y08A" source="_f9YskzICEe6TLMi6_2y08A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_f9YsqTICEe6TLMi6_2y08A"/>
        <condition xmi:type="expression:Expression" xmi:id="_f9YsqjICEe6TLMi6_2y08A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_f9YsqzICEe6TLMi6_2y08A" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_f9YsrDICEe6TLMi6_2y08A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f9YsrTICEe6TLMi6_2y08A">
        <name xmi:type="expression:Expression" xmi:id="_f9YsrjICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f9YsrzICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f9YssDICEe6TLMi6_2y08A">
        <name xmi:type="expression:Expression" xmi:id="_f9YssTICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f9YssjICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f9YsszICEe6TLMi6_2y08A">
        <name xmi:type="expression:Expression" xmi:id="_f9YstDICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f9YstTICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f9YstjICEe6TLMi6_2y08A">
        <name xmi:type="expression:Expression" xmi:id="_f9YstzICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f9YsuDICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f9YsuTICEe6TLMi6_2y08A">
        <name xmi:type="expression:Expression" xmi:id="_f9YsujICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f9YsuzICEe6TLMi6_2y08A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_f9YsvDICEe6TLMi6_2y08A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_f9YsvTICEe6TLMi6_2y08A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_f9YsvjICEe6TLMi6_2y08A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_f9YsvzICEe6TLMi6_2y08A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_f9YswDICEe6TLMi6_2y08A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_f9YswTICEe6TLMi6_2y08A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_f9YswjICEe6TLMi6_2y08A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_f9YswzICEe6TLMi6_2y08A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_f9YsxDICEe6TLMi6_2y08A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_f9YsxTICEe6TLMi6_2y08A" type="Process" element="_f9YskDICEe6TLMi6_2y08A" name="Process8" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_f9YsxjICEe6TLMi6_2y08A" type="2007" element="_f9YskTICEe6TLMi6_2y08A">
      <children xmi:type="notation:DecorationNode" xmi:id="_f9YsxzICEe6TLMi6_2y08A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_f9YsyDICEe6TLMi6_2y08A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_f9YsyTICEe6TLMi6_2y08A" type="3007" element="_f9YskjICEe6TLMi6_2y08A">
          <children xmi:type="notation:DecorationNode" xmi:id="_f9YsyjICEe6TLMi6_2y08A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_f9YsyzICEe6TLMi6_2y08A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_f9YszDICEe6TLMi6_2y08A" type="3005" element="_f9YslzICEe6TLMi6_2y08A" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f9YszTICEe6TLMi6_2y08A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f9YszjICEe6TLMi6_2y08A" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_f9YszzICEe6TLMi6_2y08A" type="3002" element="_f9YskzICEe6TLMi6_2y08A" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_f9Ys0DICEe6TLMi6_2y08A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_f9Ys0TICEe6TLMi6_2y08A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f9Ys0jICEe6TLMi6_2y08A" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_f9Ys0zICEe6TLMi6_2y08A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_f9Ys1DICEe6TLMi6_2y08A" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_f9Ys1TICEe6TLMi6_2y08A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_f9Ys1jICEe6TLMi6_2y08A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f9Ys1zICEe6TLMi6_2y08A"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_f9Ys2DICEe6TLMi6_2y08A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_f9Ys2TICEe6TLMi6_2y08A" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_f9Ys2jICEe6TLMi6_2y08A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_f9Ys2zICEe6TLMi6_2y08A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f9Ys3DICEe6TLMi6_2y08A" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_f9Ys3TICEe6TLMi6_2y08A"/>
    <edges xmi:type="notation:Connector" xmi:id="_f9Ys3jICEe6TLMi6_2y08A" type="4001" element="_f9YsqDICEe6TLMi6_2y08A" source="_f9YszzICEe6TLMi6_2y08A" target="_f9YszDICEe6TLMi6_2y08A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_f9Ys3zICEe6TLMi6_2y08A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_f9Ys4DICEe6TLMi6_2y08A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_f9Ys4TICEe6TLMi6_2y08A" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f9Ys4jICEe6TLMi6_2y08A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
